// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: api/song.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Artist string `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album  string `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
}

func (x *SongQueryRequest) Reset() {
	*x = SongQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_song_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongQueryRequest) ProtoMessage() {}

func (x *SongQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_song_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongQueryRequest.ProtoReflect.Descriptor instead.
func (*SongQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_song_proto_rawDescGZIP(), []int{0}
}

func (x *SongQueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SongQueryRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SongQueryRequest) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

type SongQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Songs []*Song `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
}

func (x *SongQueryResponse) Reset() {
	*x = SongQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_song_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongQueryResponse) ProtoMessage() {}

func (x *SongQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_song_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongQueryResponse.ProtoReflect.Descriptor instead.
func (*SongQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_song_proto_rawDescGZIP(), []int{1}
}

func (x *SongQueryResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

type Song struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Artist   string `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration string `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Album    string `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	Artwork  string `protobuf:"bytes,6,opt,name=artwork,proto3" json:"artwork,omitempty"`
	Origin   string `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	Price    string `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Song) Reset() {
	*x = Song{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_song_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_api_song_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_api_song_proto_rawDescGZIP(), []int{2}
}

func (x *Song) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Song) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Song) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Song) GetArtwork() string {
	if x != nil {
		return x.Artwork
	}
	return ""
}

func (x *Song) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Song) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

var File_api_song_proto protoreflect.FileDescriptor

var file_api_song_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x54, 0x0a, 0x10, 0x53, 0x6f, 0x6e, 0x67, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x22, 0x34, 0x0a, 0x11, 0x53,
	0x6f, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x05, 0x73, 0x6f, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x05, 0x73, 0x6f, 0x6e, 0x67,
	0x73, 0x22, 0xbc, 0x01, 0x0a, 0x04, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x32, 0x47, 0x0a, 0x0b, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x2d, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_song_proto_rawDescOnce sync.Once
	file_api_song_proto_rawDescData = file_api_song_proto_rawDesc
)

func file_api_song_proto_rawDescGZIP() []byte {
	file_api_song_proto_rawDescOnce.Do(func() {
		file_api_song_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_song_proto_rawDescData)
	})
	return file_api_song_proto_rawDescData
}

var file_api_song_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_song_proto_goTypes = []any{
	(*SongQueryRequest)(nil),  // 0: api.SongQueryRequest
	(*SongQueryResponse)(nil), // 1: api.SongQueryResponse
	(*Song)(nil),              // 2: api.Song
}
var file_api_song_proto_depIdxs = []int32{
	2, // 0: api.SongQueryResponse.songs:type_name -> api.Song
	0, // 1: api.SongService.GetSong:input_type -> api.SongQueryRequest
	1, // 2: api.SongService.GetSong:output_type -> api.SongQueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_song_proto_init() }
func file_api_song_proto_init() {
	if File_api_song_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_song_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SongQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_song_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SongQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_song_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Song); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_song_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_song_proto_goTypes,
		DependencyIndexes: file_api_song_proto_depIdxs,
		MessageInfos:      file_api_song_proto_msgTypes,
	}.Build()
	File_api_song_proto = out.File
	file_api_song_proto_rawDesc = nil
	file_api_song_proto_goTypes = nil
	file_api_song_proto_depIdxs = nil
}
